// Generated by IntelliJ-IDEA Scala plugin.
// Add settings when starting sbt from IDEA.
// Manual changes to this file will be lost.
if (java.lang.System.getProperty("idea.runid", "false") == "2017.2") scala.collection.Seq(
addSbtPlugin("org.jetbrains" % "sbt-structure-extractor" % "2017.2"),
addSbtPlugin("org.jetbrains" % "sbt-idea-shell" % "2017.2")
) else scala.collection.Seq.empty

addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.0")
addCompilerPlugin("io.tryp" % "splain" % "0.2.7" cross CrossVersion.patch)
